"""PRNG parity: assert Python's PRNG matches TS bit-exactly for 100 seeds,
20 outputs each. Golden vectors are generated by scripts/generate-golden.mjs
— if you change the PRNG algorithm, regenerate them and update both sides."""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from backend.engine_py.prng import PRNG


GOLDEN_PATH = Path(__file__).parent / "golden_vectors.json"


@pytest.fixture(scope="module")
def golden():
    return json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))


def test_scheme(golden):
    assert golden["scheme"] == "mulberry32-v1"


def test_u32_bit_exact(golden):
    mismatches: list[tuple[int, int, int, int]] = []
    for v in golden["vectors"]:
        rng = PRNG.from_seed(v["seed"])
        for i, expected in enumerate(v["u32"]):
            actual = rng.next_u32()
            if actual != expected:
                mismatches.append((v["seed"], i, expected, actual))
    assert not mismatches, f"{len(mismatches)} mismatches; first: {mismatches[:3]}"


def test_float_bit_exact(golden):
    """nextFloat = nextU32 / 2^32 — IEEE-754 division by a power of two is
    bit-exact across JS and Python."""
    mismatches: list[tuple[int, int, float, float]] = []
    for v in golden["vectors"]:
        rng = PRNG.from_seed(v["seed"])
        for i, expected in enumerate(v["floats"]):
            actual = rng.next_float()
            if not math.isclose(actual, expected, rel_tol=0, abs_tol=0):
                mismatches.append((v["seed"], i, expected, actual))
    assert not mismatches, f"{len(mismatches)} mismatches; first: {mismatches[:3]}"
